# Generated by Django 4.1.1 on 2022-11-01 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='listing',
            name='categories',
            field=models.CharField(choices=[('NA', 'None'), ('HM', 'Home'), ('CL', 'Clothes'), ('FR', 'Furniture'), ('BK', 'Bikes')], default='NA', max_length=2),
        ),
    ]
