# Generated by Django 4.1.1 on 2022-11-01 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_alter_listing_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='cats',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.category'),
        ),
    ]
