# Generated by Django 4.1.2 on 2022-11-01 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_category_listing_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='cat',
        ),
        migrations.AlterField(
            model_name='listing',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.category'),
        ),
    ]
